# Importing Libraries

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing Dataset

In [23]:
dataset = pd.read_csv('diabetes_prediction_dataset.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [24]:
print(X)

[['Female' 80.0 0 ... 25.19 6.6 140]
 ['Female' 54.0 0 ... 27.32 6.6 80]
 ['Male' 28.0 0 ... 27.32 5.7 158]
 ...
 ['Male' 66.0 0 ... 27.83 5.7 155]
 ['Female' 24.0 0 ... 35.42 4.0 100]
 ['Female' 57.0 0 ... 22.43 6.6 90]]


In [25]:
print(y)

[0 0 0 ... 0 0 0]


# Encoding Variables

In [26]:
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer

le = LabelEncoder()
dataset['smoking_history'] = le.fit_transform(dataset['smoking_history'])
dataset['gender'] = le.fit_transform(dataset['gender'])


X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [27]:
X

array([[  0.  ,  80.  ,   0.  , ...,  25.19,   6.6 , 140.  ],
       [  0.  ,  54.  ,   0.  , ...,  27.32,   6.6 ,  80.  ],
       [  1.  ,  28.  ,   0.  , ...,  27.32,   5.7 , 158.  ],
       ...,
       [  1.  ,  66.  ,   0.  , ...,  27.83,   5.7 , 155.  ],
       [  0.  ,  24.  ,   0.  , ...,  35.42,   4.  , 100.  ],
       [  0.  ,  57.  ,   0.  , ...,  22.43,   6.6 ,  90.  ]])

In [28]:
print(y)

[0 0 0 ... 0 0 0]


# Splitting the dataset into Test and Training

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Comparing the dataset

In [30]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(random_state=0,max_iter=500)
logreg.fit(X_train, y_train)
y_pred_logreg = logreg.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred_logreg))

0.96055


In [32]:
logreg.predict([[1, 55, 1, 0,3 , 28.5, 6.8, 168]])

array([1])

In [33]:
from sklearn.metrics import accuracy_score
x = 100*accuracy_score(y_test,y_pred_logreg)
print(x)

96.055
